DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  names VARCHAR(30)
);

CREATE TABLE roles(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(15,2) ,
  department_id INTEGER NOT NULL,
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (department_id) 
  REFERENCES department (id)
  ON DELETE CASCADE
);

CREATE TABLE employee(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER NOT NUll,
  manager_id INTEGER,
  CONSTRAINT FK_ROLE FOREIGN KEY (role_id)
  REFERENCES roles (id)
  ON DELETE SET NULL,
  CONSTRAINT FK_ROLE_MANAGER FOREIGN KEY (manager_id)
  REFERENCES employee (id)
  ON DELETE SET NULL
);
